name: Build and Deploy Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TAG=$(gh release view --repo OWNER/REPOSITORY --json tagName --jq '.tagName')
      
          gh release download "$TAG" \
            --repo OWNER/REPOSITORY \
            --pattern "file.zip" \
            --output "./file.zip"

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
